import { Category, Product, ProductOptionGroup } from "./types";

export const nhungCategories: Category[] = [
  {
    id: "cat-cafe",
    name: "Cafe",
    slug: "cafe",
    orderIndex: 1,
    isActive: true,
    description: "Cà phê pha phin truyền thống Đắk Lắk, cà phê muối & kem trứng béo ngậy",
  },
  {
    id: "cat-tra-sua-dam-vi",
    name: "Trà Sữa Đậm Vị",
    slug: "tra-sua-dam-vi",
    orderIndex: 2,
    isActive: true,
    description: "Trà sữa đậm vị lá trà tươi nguyên chất, béo thơm ngậy vị sữa chuẩn gu",
  },
  {
    id: "cat-tra-trai-cay",
    name: "Trà Trái Cây",
    slug: "tra-trai-cay",
    orderIndex: 3,
    isActive: true,
    description: "Trà hoa quả nhiệt đới tươi mát kết hợp Yakult và trái cây tươi giòn",
  },
  {
    id: "cat-tra-sua-mix-kem",
    name: "Trà Sữa Mix Kem",
    slug: "tra-sua-mix-kem",
    orderIndex: 4,
    isActive: true,
    description: "Trà sữa kết hợp lớp kem dừa nướng, kem trứng cháy, kem Oreo & Macchiato",
  },
  {
    id: "cat-matcha",
    name: "Matcha",
    slug: "matcha",
    orderIndex: 5,
    isActive: true,
    description: "Matcha Uji Nhật Bản nguyên chất đậm vị, thơm thanh kết hợp đậu đỏ & kiều mạch",
  },
  {
    id: "cat-sua-chua",
    name: "Sữa Chua",
    slug: "sua-chua",
    orderIndex: 6,
    isActive: true,
    description: "Sữa chua lên men tự nhiên mát lạnh, kết hợp cốm dẻo, đậu đỏ và hoa quả",
  },
  {
    id: "cat-sinh-to-nuoc-ep",
    name: "Sinh Tố - Nước Ép",
    slug: "sinh-to-nuoc-ep",
    orderIndex: 7,
    isActive: true,
    description: "Sinh tố bơ già dừa non dẻo quánh, nước cam & nước ép dứa tươi nguyên chất",
  },
  {
    id: "cat-ly-1-lit",
    name: "Ly 1 Lít",
    slug: "ly-1-lit",
    orderIndex: 8,
    isActive: true,
    description: "Đồ uống ly khổng lồ 1000ml giải nhiệt sảng khoái cực đã",
  },
  {
    id: "cat-do-an",
    name: "Đồ Ăn",
    slug: "do-an",
    orderIndex: 9,
    isActive: true,
    description: "Mì cay Hàn Quốc bốc khói đậm đà & Lạp xưởng nướng đá thơm lừng",
  },
  {
    id: "cat-topping",
    name: "Topping",
    slug: "topping",
    orderIndex: 10,
    isActive: true,
    description: "Trân châu đen dẻo, trân châu trắng ngọc trai, hạt nổ củ năng & hạt nổ yến mạch",
  },
];

// Helper tạo Option Groups cho đồ uống có 2 size M và L
const makeDrinkOptions = (priceLDiff: number = 5000, hasFlavors?: string[]): ProductOptionGroup[] => {
  const groups: ProductOptionGroup[] = [
    {
      id: `optg-size-${Math.random().toString(36).substr(2, 6)}`,
      productId: "",
      title: "Chọn Size",
      type: "RADIO",
      required: true,
      items: [
        { id: `opt-m-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "Size Vừa (M)", price: 0, isDefault: true, isAvailable: true },
        { id: `opt-l-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "Size Lớn (L)", price: priceLDiff, isDefault: false, isAvailable: true },
      ],
    },
    {
      id: `optg-sugar-${Math.random().toString(36).substr(2, 6)}`,
      productId: "",
      title: "Mức Đường",
      type: "RADIO",
      required: true,
      items: [
        { id: `sugar-100-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "100% Đường (Chuẩn vị)", price: 0, isDefault: false, isAvailable: true },
        { id: `sugar-70-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "70% Đường (Vừa ngọt)", price: 0, isDefault: true, isAvailable: true },
        { id: `sugar-50-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "50% Đường (Ít ngọt)", price: 0, isDefault: false, isAvailable: true },
        { id: `sugar-30-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "30% Đường (Thanh nhẹ)", price: 0, isDefault: false, isAvailable: true },
        { id: `sugar-0-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "0% Không đường", price: 0, isDefault: false, isAvailable: true },
      ],
    },
    {
      id: `optg-ice-${Math.random().toString(36).substr(2, 6)}`,
      productId: "",
      title: "Mức Đá",
      type: "RADIO",
      required: true,
      items: [
        { id: `ice-100-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "100% Đá (Mát lạnh)", price: 0, isDefault: true, isAvailable: true },
        { id: `ice-70-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "70% Đá", price: 0, isDefault: false, isAvailable: true },
        { id: `ice-50-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "50% Đá", price: 0, isDefault: false, isAvailable: true },
        { id: `ice-0-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "Không đá", price: 0, isDefault: false, isAvailable: true },
      ],
    },
    {
      id: `optg-top-${Math.random().toString(36).substr(2, 6)}`,
      productId: "",
      title: "Thêm Topping",
      type: "CHECKBOX",
      required: false,
      items: [
        { id: `top-tc-den-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "Trân Châu Đen", price: 5000, isAvailable: true },
        { id: `top-tc-trang-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "Trân Châu Trắng", price: 5000, isAvailable: true },
        { id: `top-no-cn-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "Hạt Nổ Củ Năng", price: 10000, isAvailable: true },
        { id: `top-no-ym-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "Hạt Nổ Yến Mạch", price: 10000, isAvailable: true },
      ],
    },
  ];

  if (hasFlavors && hasFlavors.length > 0) {
    groups.unshift({
      id: `optg-flavor-${Math.random().toString(36).substr(2, 6)}`,
      productId: "",
      title: "Chọn Hương Vị",
      type: "RADIO",
      required: true,
      items: hasFlavors.map((f, idx) => ({
        id: `opt-flav-${idx}-${Math.random().toString(36).substr(2, 6)}`,
        groupId: "",
        name: f,
        price: 0,
        isDefault: idx === 0,
        isAvailable: true,
      })),
    });
  }

  return groups;
};

// Helper cho món 1 size duy nhất
const makeSingleSizeOptions = (sizeLabel: string = "Ly Lớn (L)"): ProductOptionGroup[] => [
  {
    id: `optg-sugar-${Math.random().toString(36).substr(2, 6)}`,
    productId: "",
    title: "Mức Đường",
    type: "RADIO",
    required: true,
    items: [
      { id: `sugar-100-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "100% Đường (Chuẩn vị)", price: 0, isDefault: true, isAvailable: true },
      { id: `sugar-70-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "70% Đường", price: 0, isDefault: false, isAvailable: true },
      { id: `sugar-50-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "50% Đường (Ít ngọt)", price: 0, isDefault: false, isAvailable: true },
      { id: `sugar-0-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "0% Không đường", price: 0, isDefault: false, isAvailable: true },
    ],
  },
  {
    id: `optg-ice-${Math.random().toString(36).substr(2, 6)}`,
    productId: "",
    title: "Mức Đá",
    type: "RADIO",
    required: true,
    items: [
      { id: `ice-100-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "100% Đá", price: 0, isDefault: true, isAvailable: true },
      { id: `ice-70-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "70% Đá", price: 0, isDefault: false, isAvailable: true },
      { id: `ice-0-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "Không đá", price: 0, isDefault: false, isAvailable: true },
    ],
  },
  {
    id: `optg-top-${Math.random().toString(36).substr(2, 6)}`,
    productId: "",
    title: "Thêm Topping",
    type: "CHECKBOX",
    required: false,
    items: [
      { id: `top-tc-den-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "Trân Châu Đen", price: 5000, isAvailable: true },
      { id: `top-tc-trang-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "Trân Châu Trắng", price: 5000, isAvailable: true },
      { id: `top-no-cn-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "Hạt Nổ Củ Năng", price: 10000, isAvailable: true },
      { id: `top-no-ym-${Math.random().toString(36).substr(2, 6)}`, groupId: "", name: "Hạt Nổ Yến Mạch", price: 10000, isAvailable: true },
    ],
  },
];

export const nhungProducts: Product[] = [
  // ==================== 1. CAFE (4 món) ====================
  {
    id: "nhung-cafe-1",
    name: "Nâu",
    description: "Cà phê Robusta Đắk Lắk pha phin truyền thống kết hợp sữa đặc ngọt béo sánh mịn.",
    price: 20000,
    image: "/image/nâu.jpg",
    categoryId: "cat-cafe",
    categoryName: "Cafe",
    isAvailable: true,
    isFeatured: false,
    salesCount: 88,
    options: makeDrinkOptions(0),
  },
  {
    id: "nhung-cafe-2",
    name: "Bạc Xỉu",
    description: "Vị sữa tươi béo ngậy hòa quyện chút hương cà phê phin nồng nàn êm dịu.",
    price: 20000,
    image: "/image/bạc xỉu.jpg",
    categoryId: "cat-cafe",
    categoryName: "Cafe",
    isAvailable: true,
    isFeatured: false,
    salesCount: 112,
    options: makeDrinkOptions(0),
  },
  {
    id: "nhung-cafe-3",
    name: "Muối",
    description: "Cà phê muối kem béo thơm lừng, vị mặn nhẹ quyện cùng cà phê sánh béo đậm đà.",
    price: 25000,
    image: "/image/muối.jpg",
    categoryId: "cat-cafe",
    categoryName: "Cafe",
    isAvailable: true,
    isFeatured: false,
    salesCount: 145,
    options: makeDrinkOptions(0),
  },
  {
    id: "nhung-cafe-4",
    name: "Kem Trứng",
    description: "Lớp kem trứng đánh bông vàng ươm béo ngậy phủ trên nền cà phê phin đậm đà thơm ngát.",
    price: 25000,
    image: "/image/kem trứng.jpg",
    categoryId: "cat-cafe",
    categoryName: "Cafe",
    isAvailable: true,
    isFeatured: false,
    salesCount: 76,
    options: makeDrinkOptions(0),
  },

  // ==================== 2. TRÀ SỮA ĐẬM VỊ (6 món) ====================
  {
    id: "nhung-ts-5",
    name: "Olong Nhài Sữa",
    description: "Hương trà ô long hoa nhài thơm ngát kết hợp sữa béo ngậy chuẩn vị Nhung Trà.",
    price: 25000,
    image: "/image/Olong nhài sữa.jpg",
    categoryId: "cat-tra-sua-dam-vi",
    categoryName: "Trà Sữa Đậm Vị",
    isAvailable: true,
    isFeatured: true,
    salesCount: 250,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-ts-6",
    name: "Hồng Trà Sữa",
    description: "Hồng trà ủ truyền thống đậm vị chát nhẹ hòa cùng vị sữa thơm ngọt đậm đà.",
    price: 23000,
    image: "/image/hồng trà sữa.jpg",
    categoryId: "cat-tra-sua-dam-vi",
    categoryName: "Trà Sữa Đậm Vị",
    isAvailable: true,
    isFeatured: false,
    salesCount: 165,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-ts-7",
    name: "Olong Nhài Xoài",
    description: "Trà ô long nhài thanh khiết kết hợp sốt xoài nhiệt đới chín thơm ngọt ngào.",
    price: 30000,
    image: "/image/olong nhài xoài.jpg",
    categoryId: "cat-tra-sua-dam-vi",
    categoryName: "Trà Sữa Đậm Vị",
    isAvailable: true,
    isFeatured: true,
    salesCount: 230,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-ts-8",
    name: "Trà Sữa Nướng",
    description: "Trà sữa sao nướng thơm lừng hương caramel quyến rũ, béo thơm đậm vị khó quên.",
    price: 30000,
    image: "/image/trà sữa nướng.jpg",
    categoryId: "cat-tra-sua-dam-vi",
    categoryName: "Trà Sữa Đậm Vị",
    isAvailable: true,
    isFeatured: true,
    salesCount: 238,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-ts-9",
    name: "Olong Đậu Đỏ",
    description: "Trà ô long sữa béo ngọt kèm topping đậu đỏ bùi thơm mềm mịn ninh nhừ.",
    price: 30000,
    image: "/image/Olong đậu đỏ.jpg",
    categoryId: "cat-tra-sua-dam-vi",
    categoryName: "Trà Sữa Đậm Vị",
    isAvailable: true,
    isFeatured: true,
    salesCount: 210,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-ts-10",
    name: "Trà Sữa Chọn Vị",
    description: "Tùy chọn hương vị yêu thích: Dâu tây, Việt Quất, Xoài nhiệt đới hoặc Đào thơm lừng.",
    price: 30000,
    image: "/image/trà dâu.jpg",
    categoryId: "cat-tra-sua-dam-vi",
    categoryName: "Trà Sữa Đậm Vị",
    isAvailable: true,
    isFeatured: false,
    salesCount: 130,
    options: makeDrinkOptions(5000, ["Vị Dâu Tây", "Vị Việt Quất", "Vị Xoài Nhiệt Đới", "Vị Đào Thơm"]),
  },

  // ==================== 3. TRÀ TRÁI CÂY (7 món) ====================
  {
    id: "nhung-tc-11",
    name: "Dâu Tằm Yakult",
    description: "Dâu tằm tươi chua ngọt tự nhiên kết hợp sữa chua men sống Yakult thanh mát tốt cho tiêu hóa.",
    price: 30000,
    image: "/image/dâu tằm yakult.jpg",
    categoryId: "cat-tra-trai-cay",
    categoryName: "Trà Trái Cây",
    isAvailable: true,
    isFeatured: false,
    salesCount: 175,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-tc-12",
    name: "Xoài Yakult",
    description: "Thịt xoài chín vàng xay nhuyễn cùng sữa chua Yakult chua ngọt sảng khoái mát lạnh.",
    price: 30000,
    image: "/image/xoài yakult.jpg",
    categoryId: "cat-tra-trai-cay",
    categoryName: "Trà Trái Cây",
    isAvailable: true,
    isFeatured: false,
    salesCount: 95,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-tc-13",
    name: "Trà Đào",
    description: "Trà đào thơm lừng hương quả nhiệt đới, miếng đào ngâm giòn ngọt thanh mát.",
    price: 25000,
    image: "/image/trà đào.jpg",
    categoryId: "cat-tra-trai-cay",
    categoryName: "Trà Trái Cây",
    isAvailable: true,
    isFeatured: false,
    salesCount: 160,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-tc-14",
    name: "Trà Dứa",
    description: "Nước cốt dứa thơm tươi dầm mát lạnh hòa quyện cùng cốt trà lài thơm nức mũi.",
    price: 30000,
    image: "/image/trà dứa.jpg",
    categoryId: "cat-tra-trai-cay",
    categoryName: "Trà Trái Cây",
    isAvailable: true,
    isFeatured: false,
    salesCount: 110,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-tc-15",
    name: "Trà Tắc Xí Muội",
    description: "Vị chua thanh của tắc tươi kết hợp xí muội mặn mòi đã khát (Ly lớn L).",
    price: 18000,
    image: "/image/tắc xí muội.jpg",
    categoryId: "cat-tra-trai-cay",
    categoryName: "Trà Trái Cây",
    isAvailable: true,
    isFeatured: false,
    salesCount: 110,
    options: makeSingleSizeOptions("Size Lớn (L)"),
  },
  {
    id: "nhung-tc-16",
    name: "Trà Chanh",
    description: "Trà chanh truyền thống chua dịu thanh mát, giải nhiệt mùa hè cực sảng khoái (Ly lớn L).",
    price: 15000,
    image: "https://images.unsplash.com/photo-1556881286-fc6915169721?w=600&auto=format&fit=crop&q=80",
    categoryId: "cat-tra-trai-cay",
    categoryName: "Trà Trái Cây",
    isAvailable: true,
    isFeatured: false,
    salesCount: 88,
    options: makeSingleSizeOptions("Size Lớn (L)"),
  },
  {
    id: "nhung-tc-17",
    name: "Trà Sen Vàng Củ Năng",
    description: "Trà sen thơm dịu thanh tao, hạt sen bùi béo kết hợp củ năng giòn sần sật.",
    price: 25000,
    image: "/image/trà sen vàng củ năng.jpg",
    categoryId: "cat-tra-trai-cay",
    categoryName: "Trà Trái Cây",
    isAvailable: true,
    isFeatured: false,
    salesCount: 145,
    options: makeDrinkOptions(5000),
  },

  // ==================== 4. TRÀ SỮA MIX KEM (9 món) ====================
  {
    id: "nhung-mk-18",
    name: "Olong Nhài Kem Dừa Nướng",
    description: "Cốt trà ô long nhài phủ lớp kem dừa béo ngậy và vụn dừa nướng giòn rụm thơm phức.",
    price: 30000,
    image: "/image/long nhài kem dừa nướng.jpg",
    categoryId: "cat-tra-sua-mix-kem",
    categoryName: "Trà Sữa Mix Kem",
    isAvailable: true,
    isFeatured: true,
    salesCount: 245,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-mk-19",
    name: "Hồng Trà Kem Trứng Dừa Nướng",
    description: "Hồng trà đậm vị phủ kem trứng cháy thơm lừng kèm dừa nướng giòn tan béo ngậy.",
    price: 30000,
    image: "/image/hồng trà kem trứng dừa nướng.jpg",
    categoryId: "cat-tra-sua-mix-kem",
    categoryName: "Trà Sữa Mix Kem",
    isAvailable: true,
    isFeatured: false,
    salesCount: 130,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-mk-20",
    name: "Hồng Trà Kem Oreo",
    description: "Hồng trà sữa thơm béo phủ lớp kem tuyết mềm mịn và vụn bánh quy Oreo giòn rụm.",
    price: 28000,
    image: "/image/hồng trà kem oreo.jpg",
    categoryId: "cat-tra-sua-mix-kem",
    categoryName: "Trà Sữa Mix Kem",
    isAvailable: true,
    isFeatured: false,
    salesCount: 155,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-mk-21",
    name: "Trà Sữa Sốt Khoai Môn Yến Mạch",
    description: "Xốt khoai môn dẻo bùi thơm lừng hòa quyện cùng sữa béo và yến mạch bổ dưỡng.",
    price: 30000,
    image: "/image/trà sữa sốt khoai môn yến mạch.jpg",
    categoryId: "cat-tra-sua-mix-kem",
    categoryName: "Trà Sữa Mix Kem",
    isAvailable: true,
    isFeatured: true,
    salesCount: 240,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-mk-22",
    name: "Olong Nhài Hạnh Nhân",
    description: "Trà ô long nhài thơm hương hoa lài, hòa cùng sữa hạnh nhân béo bùi thanh nhẹ.",
    price: 30000,
    image: "/image/Olong nhài hạnh nhân.jpg",
    categoryId: "cat-tra-sua-mix-kem",
    categoryName: "Trà Sữa Mix Kem",
    isAvailable: true,
    isFeatured: true,
    salesCount: 215,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-mk-23",
    name: "Olong Nhài Cốm",
    description: "Hương vị trà ô long nhài kết hợp cốm non Hà Nội dẻo bùi thơm ngát.",
    price: 34000,
    image: "/image/Olong nhài cốm.jpg",
    categoryId: "cat-tra-sua-mix-kem",
    categoryName: "Trà Sữa Mix Kem",
    isAvailable: true,
    isFeatured: true,
    salesCount: 220,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-mk-24",
    name: "Ovatine Machiato",
    description: "Ovaltine socola mạch nha thơm lừng phủ lớp kem phô mai Macchiato mằn mặn béo ngậy.",
    price: 30000,
    image: "/image/Ovatine Machiato.jpg",
    categoryId: "cat-tra-sua-mix-kem",
    categoryName: "Trà Sữa Mix Kem",
    isAvailable: true,
    isFeatured: false,
    salesCount: 118,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-mk-25",
    name: "Choco Phomai Kem Mặn",
    description: "Socola nguyên chất đậm vị đắng ngọt hòa quyện lớp kem phô mai sánh mịn béo mặn cuốn hút.",
    price: 34000,
    image: "/image/Choco Phomai kem Mặn.jpg",
    categoryId: "cat-tra-sua-mix-kem",
    categoryName: "Trà Sữa Mix Kem",
    isAvailable: true,
    isFeatured: true,
    salesCount: 242,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-mk-26",
    name: "Milo Dầm",
    description: "Bột Milo socola dầm đá tuyết mát lạnh, đẫm sốt cacao đặc quánh thơm lừng.",
    price: 30000,
    image: "/image/milo dầm.jpg",
    categoryId: "cat-tra-sua-mix-kem",
    categoryName: "Trà Sữa Mix Kem",
    isAvailable: true,
    isFeatured: false,
    salesCount: 160,
    options: makeSingleSizeOptions("Size Vừa (30k)"),
  },

  // ==================== 5. MATCHA (4 món) ====================
  {
    id: "nhung-mat-27",
    name: "Matcha Latte",
    description: "Bột matcha Uji nguyên chất thơm thanh hòa quyện sữa tươi thanh trùng béo ngậy chuẩn Nhật.",
    price: 30000,
    image: "/image/matcha latte.jpg",
    categoryId: "cat-matcha",
    categoryName: "Matcha",
    isAvailable: true,
    isFeatured: false,
    salesCount: 155,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-mat-28",
    name: "Matcha Kiều Mạch",
    description: "Matcha thơm lừng kết hợp hạt kiều mạch rang giòn tan bùi bùi thanh mát.",
    price: 30000,
    image: "/image/matcha kiều mạch.jpg",
    categoryId: "cat-matcha",
    categoryName: "Matcha",
    isAvailable: true,
    isFeatured: false,
    salesCount: 82,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-mat-29",
    name: "Matcha Đậu Đỏ",
    description: "Sự kết hợp kinh điển giữa matcha đậm vị và đậu đỏ Azuki ninh nhừ ngọt bùi thơm mềm.",
    price: 30000,
    image: "/image/matcha đậu đỏ.jpg",
    categoryId: "cat-matcha",
    categoryName: "Matcha",
    isAvailable: true,
    isFeatured: false,
    salesCount: 120,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-mat-30",
    name: "Matcha Kem Oreo",
    description: "Matcha latte phủ lớp kem tuyết béo ngậy và vụn bánh quy Oreo socola giòn ngon sảng khoái.",
    price: 30000,
    image: "/image/matcha kem oreo.jpg",
    categoryId: "cat-matcha",
    categoryName: "Matcha",
    isAvailable: true,
    isFeatured: false,
    salesCount: 140,
    options: makeDrinkOptions(5000),
  },

  // ==================== 6. SỮA CHUA (5 món) ====================
  {
    id: "nhung-sc-31",
    name: "Sữa Chua Muối Kiều Mạch",
    description: "Sữa chua lên men tự nhiên với chút vị muối mặn nhẹ và hạt kiều mạch giòn rụm thanh mát.",
    price: 30000,
    image: "/image/sữa chua muối kiều mạch.jpg",
    categoryId: "cat-sua-chua",
    categoryName: "Sữa Chua",
    isAvailable: true,
    isFeatured: true,
    salesCount: 235,
    options: makeSingleSizeOptions("Ly Vừa (30.000đ)"),
  },
  {
    id: "nhung-sc-32",
    name: "Sữa Chua Thường Kiều Mạch",
    description: "Sữa chua truyền thống chua ngọt thanh mát ăn kèm kiều mạch bùi giòn đã khát.",
    price: 30000,
    image: "/image/sữa chua thường kiều mạch.jpg",
    categoryId: "cat-sua-chua",
    categoryName: "Sữa Chua",
    isAvailable: true,
    isFeatured: true,
    salesCount: 225,
    options: makeSingleSizeOptions("Ly Vừa (30.000đ)"),
  },
  {
    id: "nhung-sc-33",
    name: "Sữa Chua Đậu Đỏ",
    description: "Sữa chua sánh mịn kết hợp đậu đỏ bùi ngọt dẻo thơm mát lạnh.",
    price: 30000,
    image: "/image/sữa chua đậu đỏ.jpg",
    categoryId: "cat-sua-chua",
    categoryName: "Sữa Chua",
    isAvailable: true,
    isFeatured: false,
    salesCount: 115,
    options: makeSingleSizeOptions("Ly Vừa (30.000đ)"),
  },
  {
    id: "nhung-sc-34",
    name: "Sữa Chua Cốm Dẻo",
    description: "Sữa chua dẻo sánh mịn ăn cùng cốm non Hà Nội dẻo thơm ngát đặc sản.",
    price: 39000,
    image: "/image/sữa chua cốm dẻo.jpg",
    categoryId: "cat-sua-chua",
    categoryName: "Sữa Chua",
    isAvailable: true,
    isFeatured: false,
    salesCount: 128,
    options: makeSingleSizeOptions("Ly Đặc Biệt (39.000đ)"),
  },
  {
    id: "nhung-sc-35",
    name: "Sữa Chua Chọn Vị",
    description: "Sữa chua hoa quả nhiệt đới tùy chọn: Dâu tây, Việt Quất, Xoài chín hoặc Đào thơm.",
    price: 30000,
    image: "/image/sữa chua chọn vị.jpg",
    categoryId: "cat-sua-chua",
    categoryName: "Sữa Chua",
    isAvailable: true,
    isFeatured: false,
    salesCount: 104,
    options: makeDrinkOptions(0, ["Vị Dâu Tây", "Vị Việt Quất", "Vị Xoài Nhiệt Đới", "Vị Đào Thơm"]),
  },

  // ==================== 7. SINH TỐ - NƯỚC ÉP (7 món) ====================
  {
    id: "nhung-st-36",
    name: "Bơ",
    description: "Sinh tố bơ sáp Đắk Lắk dẻo quánh béo ngậy thơm lừng phủ dừa sấy.",
    price: 30000,
    image: "/image/bơ.jpg",
    categoryId: "cat-sinh-to-nuoc-ep",
    categoryName: "Sinh Tố - Nước Ép",
    isAvailable: true,
    isFeatured: false,
    salesCount: 190,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-st-37",
    name: "Xoài",
    description: "Sinh tố xoài cát chín vàng ngọt lịm, sánh mịn mát lạnh sảng khoái.",
    price: 30000,
    image: "/image/xoài.jpg",
    categoryId: "cat-sinh-to-nuoc-ep",
    categoryName: "Sinh Tố - Nước Ép",
    isAvailable: true,
    isFeatured: false,
    salesCount: 140,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-st-38",
    name: "Bơ Già Dừa Non",
    description: "Bơ già béo dẻo xay cùng cơm dừa non sần sật bùi ngậy độc đáo vị ngon cuốn hút.",
    price: 30000,
    image: "/image/bơ già dừa non.jpg",
    categoryId: "cat-sinh-to-nuoc-ep",
    categoryName: "Sinh Tố - Nước Ép",
    isAvailable: true,
    isFeatured: true,
    salesCount: 248,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-st-39",
    name: "Mãng Cầu",
    description: "Sinh tố mãng cầu xiêm chua ngọt thanh tao sánh mịn, giải nhiệt cực đã.",
    price: 30000,
    image: "/image/mãng cầu.jpg",
    categoryId: "cat-sinh-to-nuoc-ep",
    categoryName: "Sinh Tố - Nước Ép",
    isAvailable: true,
    isFeatured: false,
    salesCount: 96,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-st-40",
    name: "Dừa",
    description: "Sinh tố dừa tươi xay nhuyễn ngọt thanh, thơm béo hương nước cốt dừa tự nhiên.",
    price: 30000,
    image: "/image/dừa.jpg",
    categoryId: "cat-sinh-to-nuoc-ep",
    categoryName: "Sinh Tố - Nước Ép",
    isAvailable: true,
    isFeatured: false,
    salesCount: 88,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-st-41",
    name: "Nước Cam",
    description: "Nước cam vắt tươi nguyên chất giàu Vitamin C tăng cường đề kháng mỗi ngày.",
    price: 25000,
    image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80",
    categoryId: "cat-sinh-to-nuoc-ep",
    categoryName: "Sinh Tố - Nước Ép",
    isAvailable: true,
    isFeatured: false,
    salesCount: 130,
    options: makeDrinkOptions(5000),
  },
  {
    id: "nhung-st-42",
    name: "Ép Dứa",
    description: "Nước ép dứa mật nguyên chất tươi mát chua ngọt thanh dịu giải khát.",
    price: 25000,
    image: "/image/ép dứa.jpg",
    categoryId: "cat-sinh-to-nuoc-ep",
    categoryName: "Sinh Tố - Nước Ép",
    isAvailable: true,
    isFeatured: false,
    salesCount: 92,
    options: makeDrinkOptions(5000),
  },

  // ==================== 8. LY 1 LÍT (2 món) ====================
  {
    id: "nhung-lit-43",
    name: "Me Đá",
    description: "Me đá ly khổng lồ 1 Lít chua ngọt đậm đà, kèm đậu phộng rang giòn thơm bùi.",
    price: 25000,
    image: "/image/me đá.jpg",
    categoryId: "cat-ly-1-lit",
    categoryName: "Ly 1 Lít",
    isAvailable: true,
    isFeatured: false,
    salesCount: 180,
    options: makeSingleSizeOptions("Ly 1 Lít (1000ml)"),
  },
  {
    id: "nhung-lit-44",
    name: "Tắc Xí Muội",
    description: "Tắc xí muội ly khổng lồ 1 Lít uống cực đã, giải khát tức thì ngày nắng nóng.",
    price: 25000,
    image: "/image/tắc xí muội.jpg",
    categoryId: "cat-ly-1-lit",
    categoryName: "Ly 1 Lít",
    isAvailable: true,
    isFeatured: false,
    salesCount: 155,
    options: makeSingleSizeOptions("Ly 1 Lít (1000ml)"),
  },

  // ==================== 9. ĐỒ ĂN (5 món) ====================
  {
    id: "nhung-food-45",
    name: "Lạp Xưởng Nướng (60k/ 5 cái)",
    description: "Lạp xưởng nướng đá Hà Khẩu thơm lừng, giòn sần sật đậm đà gia vị thảo mộc kèm ớt bột.",
    price: 60000,
    image: "/image/lạp xưởng nướng.jpg",
    categoryId: "cat-do-an",
    categoryName: "Đồ Ăn",
    isAvailable: true,
    isFeatured: false,
    salesCount: 210,
    options: [],
  },
  {
    id: "nhung-food-46",
    name: "Mì Cay Xúc Xích",
    description: "Mì cay chuẩn vị Hàn Quốc cay tê đậm đà kết hợp xúc xích thơm ngon, phù hợp cho một bữa ăn nhanh.",
    price: 30000,
    image: "/image/mì cay xúc xích.jpg",
    categoryId: "cat-do-an",
    categoryName: "Đồ Ăn",
    isAvailable: true,
    isFeatured: false,
    salesCount: 95,
    options: [],
  },
  {
    id: "nhung-food-47",
    name: "Mỳ Cay Dồi Sụn Xúc Xích",
    description: "Mì cay kết hợp dồi sụn giòn sần sật và xúc xích, nước dùng thố sôi sùng sục đậm vị cay nồng.",
    price: 35000,
    image: "/image/mì cay dồi sụn xúc xích.jpg",
    categoryId: "cat-do-an",
    categoryName: "Đồ Ăn",
    isAvailable: true,
    isFeatured: false,
    salesCount: 135,
    options: [],
  },
  {
    id: "nhung-food-48",
    name: "Mỳ Cay Bò Xúc Xích",
    description: "Mì cay thơm lừng kết hợp thịt bò tươi mềm ngọt và xúc xích đậm đà.",
    price: 40000,
    image: "/image/mỳ cay bò xúc xích.jpg",
    categoryId: "cat-do-an",
    categoryName: "Đồ Ăn",
    isAvailable: true,
    isFeatured: false,
    salesCount: 125,
    options: [],
  },
  {
    id: "nhung-food-49",
    name: "Mỳ Cay Thập Cẩm",
    description: "Mì cay thố thập cẩm đầy đặn nhiều nguyên liệu: thịt bò, dồi sụn, xúc xích và rau củ tươi ngon cay nồng.",
    price: 45000,
    image: "/image/mì cay thập cẩm.jpg",
    categoryId: "cat-do-an",
    categoryName: "Đồ Ăn",
    isAvailable: true,
    isFeatured: false,
    salesCount: 160,
    options: [],
  },

  // ==================== 10. TOPPING (4 món) ====================
  {
    id: "nhung-top-50",
    name: "Trân Châu Trắng",
    description: "Trân châu ngọc trai giòn sần sật, vị ngọt thanh nhẹ nhàng dai giòn.",
    price: 5000,
    image: "/image/trân châu trắng.png",
    categoryId: "cat-topping",
    categoryName: "Topping",
    isAvailable: true,
    isFeatured: false,
    salesCount: 220,
    options: [],
  },
  {
    id: "nhung-top-51",
    name: "Trân Châu Đen",
    description: "Trân châu đường đen truyền thống dẻo dai ngọt thơm đậm đà.",
    price: 5000,
    image: "/image/trân châu đen.png",
    categoryId: "cat-topping",
    categoryName: "Topping",
    isAvailable: true,
    isFeatured: false,
    salesCount: 280,
    options: [],
  },
  {
    id: "nhung-top-52",
    name: "Hạt Nổ Củ Năng",
    description: "Hạt củ năng bọc bột lọc giòn ngọt, cắn nổ bung vị thơm thanh mát.",
    price: 10000,
    image: "/image/Hạt nổ củ năng.jpg",
    categoryId: "cat-topping",
    categoryName: "Topping",
    isAvailable: true,
    isFeatured: false,
    salesCount: 160,
    options: [],
  },
  {
    id: "nhung-top-53",
    name: "Hạt Nổ Yến Mạch",
    description: "Hạt nổ yến mạch dinh dưỡng bùi béo, thơm lừng hương ngũ cốc tự nhiên.",
    price: 10000,
    image: "/image/hạt nổ yến mạch.jpg",
    categoryId: "cat-topping",
    categoryName: "Topping",
    isAvailable: true,
    isFeatured: false,
    salesCount: 140,
    options: [],
  },
];
